### ISSUE TITLE
Incomplete RuntimeGC compatibility

### ISSUE THREAD

**Issue by AndShy** [Vectorial1024/Desynchronized#20]
just error. idk what it affect for, but hugslib show debug log
https://gist.github.com/HugsLibRecordKeeper/26a175e3b3a557a0d6ace2d1a935a9f7#file-output_log-txt-L2005

**Comment by Vectorial1024** [comment]
The error is caused by the premature v1.5.2 update that I have uploaded a few days ago. It seems that I have forgotten to double-check whether my work is complete before uploading the mod.

However, I have run into some complications when attempting to fix this error, and it seems the complications come from Harmony's side. I have reported the complication to Harmony. Refer to this Issue: https://github.com/pardeike/Harmony/issues/193

Depending on the situation, I may have to cancel the RuntimeGC compatibility for now and re-introduce it for future versions.

**Comment by AndShy** [comment]
after i fixed other errors hugslib no longer show console log.
another fact that the RuntimeGC not installed in my mod pack. looks like Desynchronized trying patch mod that not exist.

**Comment by Vectorial1024** [comment]
Yes, I assumed that RuntimeGC is installed in the users' side when making that patch, so for those who do not have RuntimeGC (e.g. you) the game throws an error.

I am trying to fix this for those without RuntimeGC but it seems we are having some difficulties.

UPDATE: I have found a workaround to the Harmony library problem. We can resume work.

**Comment by Vectorial1024** [comment]
The error messages problem is fixed.

The fix is contained in the upcoming v1.5.3 .

UPDATE: Specifically, the C# patch file now dynamically targets RuntimeGC, and prevents Harmony from processing the patch if RuntimeGC is not found. Still, to ensure safety and compatibility, this mod should be loaded after RuntimeGC. The Mod Manager `manifest.xml` should contain instructions to load this mod after RuntimeGC.
